name: automerge
on:
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  automerge-test1:
    if: ${{ github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
    - run: gh pr merge $GITHUB_HEAD_REF --squash --auto --delete-branch
  automerge-test2:
    runs-on: ubuntu-latest
    if: ${{ github.event.checks.conclusion == 'success' }} 
    steps:
    - run: gh pr merge $GITHUB_HEAD_REF --squash --auto --delete-branch
  automerge-test3:
    runs-on: ubuntu-latest
    steps:
    - run: gh pr merge $GITHUB_HEAD_REF --squash --auto --delete-branch
